export class GlobalStats {
  public static NOME_REGIONAL;
  public static REDE = [
    {
      "nomeUnidade": "CENTRO NOERTE",
      "nomeEmissor": "EMISSOR PADRÃO",
      "tme": 1800,
      "qca": 5320,
      "paa": 50,
      "status": 0,
      "qce": 1000,
      "qtma": 4,
      "qsc": 100,
      "totalCritico": 25,
      "totalAlerta": 7,
      "totalNormal": 2,
      "totalOffLine": 20,
      "codigoUnidadePai": 1,
      "codigoUnidade": 1000,
      "nivelUnidade": 2,
      "uf": "DF",
      "totalChamadas": 0,
      "emissorID": 0,
      "latitude": "",
      "longitude": "",
      "endereco": "CARGA INICIAL",
      "municipio": "SAO PAULO(CAPITAL)"
    },
    {
      "nomeUnidade": "LESTE",
      "nomeEmissor": "EMISSOR PADRÃO",
      "tme": 120,
      "qca": 8491,
      "paa": 90,
      "status": 0,
      "qce": 2000,
      "qtma": 3,
      "qsc": 200,
      "totalCritico": 16,
      "totalAlerta": 8,
      "totalNormal": 131,
      "totalOffLine": 18,
      "codigoUnidadePai": 1,
      "codigoUnidade": 2000,
      "nivelUnidade": 2,
      "uf": "RR",
      "totalChamadas": 0,
      "emissorID": 0,
      "latitude": "",
      "longitude": "",
      "endereco": "CARGA INICIAL",
      "municipio": "SAO PAULO(CAPITAL)",
    },
    {
      "nomeUnidade": "NORDESTE",
      "nomeEmissor": "EMISSOR PADRÃO",
      "tme": 1200,
      "qca": 4853,
      "paa": 10,
      "status": 0,
      "qce": 3000,
      "qtma": 23,
      "qsc": 300,
      "totalCritico": 12,
      "totalAlerta": 2,
      "totalNormal": 59,
      "totalOffLine": 8,
      "codigoUnidadePai": 1,
      "codigoUnidade": 3000,
      "nivelUnidade": 2,
      "uf": "AL",
      "totalChamadas": 0,
      "emissorID": 0,
      "latitude": "",
      "longitude": "",
      "endereco": "CARGA INICIAL",
      "municipio": "SAO PAULO(CAPITAL)",
    }
  ];

  public static REGIONAL = [
    {
      "nomeUnidade": "BRASILIA",
      "nomeEmissor": "EMISSOR PADRÃO",
      "tme": 120,
      "qca": 871,
      "paa": 100,
      "status": 0,
      "qce": 1000,
      "qtma": 4,
      "qsc": 0,
      "totalCritico": 2,
      "totalAlerta": 0,
      "totalNormal": 101,
      "totalOffLine": 21,
      "codigoUnidadePai": 1000,
      "codigoUnidade": 10,
      "nivelUnidade": 1,
      "uf": "DF",
      "totalChamadas": 0,
      "emissorID": 0,
      "latitude": "",
      "longitude": "",
      "endereco": "CARGA INICIAL",
      "municipio": "SAO PAULO(CAPITAL)"
    },
    {
      "nomeUnidade": "CAMPO GRANDE",
      "nomeEmissor": "EMISSOR PADRÃO",
      "tme": 120,
      "qca": 617,
      "paa": 50,
      "status": 0,
      "qce": 1,
      "qtma": 0,
      "qsc": 2,
      "totalCritico": 2,
      "totalAlerta": 0,
      "totalNormal": 131,
      "totalOffLine": 20,
      "codigoUnidadePai": 2000,
      "codigoUnidade": 20,
      "nivelUnidade": 1,
      "uf": "RR",
      "totalChamadas": 0,
      "emissorID": 0,
      "latitude": "",
      "longitude": "",
      "endereco": "CARGA INICIAL",
      "municipio": "SAO PAULO(CAPITAL)",
    },
    {
      "nomeUnidade": "CUIABA",
      "nomeEmissor": "EMISSOR PADRÃO",
      "tme": 120,
      "qca": 813,
      "paa": 76,
      "status": 0,
      "qce": 1,
      "qtma": 0,
      "qsc": 2,
      "totalCritico": 2,
      "totalAlerta": 1,
      "totalNormal": 59,
      "totalOffLine":17,
      "codigoUnidadePai": 3000,
      "codigoUnidade": 30,
      "nivelUnidade": 1,
      "uf": "AL",
      "totalChamadas": 0,
      "emissorID": 0,
      "latitude": "",
      "longitude": "",
      "endereco": "CARGA INICIAL",
      "municipio": "SAO PAULO(CAPITAL)",
    },
    {
      "nomeUnidade": "GIOANIA",
      "nomeEmissor": "EMISSOR PADRÃO",
      "tme": 120,
      "qca": 1427,
      "paa": 30,
      "status": 0,
      "qce": 1,
      "qtma": 0,
      "qsc": 2,
      "totalCritico": 1,
      "totalAlerta": 0,
      "totalNormal": 143,
      "totalOffLine":21,
      "codigoUnidadePai": 3000,
      "codigoUnidade": 40,
      "nivelUnidade": 1,
      "uf": "AL",
      "totalChamadas": 0,
      "emissorID": 0,
      "latitude": "",
      "longitude": "",
      "endereco": "CARGA INICIAL",
      "municipio": "SAO PAULO(CAPITAL)",
    }
  ];

  public static AGENCIA = [
    {
      "emissorID": 5,
      "nomeUnidade": "ARAGUAINA",
      "nivelUnidade": 9,
      "codigoUnidade": 1,
      "codigoUnidadePai": 10,
      "nomeEmissor": "L076LXDZX8TPDMW",
      "tme": 120,
      "qca": 150,
      "paa": 0,
      "totalCritico": 5,
      "totalAlerta": 7,
      "totalNormal": 34,
      "totalOffLine": 2,
      "totalChamadas": 0,
      "status": 0,
      "qce": 0,
      "qtma": 0,
      "qsc": 0,
      "endereco": "RUA DONA ANA NERI 368",
      "municipio": "SAO PAULO(CAPITAL)",
      "uf": "SP",
      "latitude": "",
      "longitude": ""
    },
    {
      "emissorID": 5,
      "nomeUnidade": "REDENCAO",
      "nivelUnidade": 9,
      "codigoUnidade": 1,
      "codigoUnidadePai": 2,
      "nomeEmissor": "L076LXDZX8TPDMW",
      "tme": 120,
      "qca": 150,
      "paa": 0,
      "totalCritico": 14,
      "totalAlerta": 3,
      "totalNormal": 56,
      "totalOffLine": 7,
      "totalChamadas": 0,
      "status": 0,
      "qce": 0,
      "qtma": 0,
      "qsc": 0,
      "endereco": "RUA DONA ANA NERI 368",
      "municipio": "SAO PAULO(CAPITAL)",
      "uf": "SP",
      "latitude": "",
      "longitude": ""
    }
  ];
}
